version: '3.8'
services:
  db:
    image: postgres:14
    container_name: txnfeesdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: txnfeesdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - db
    build:
      context: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - BINANCE_WSS_URL=$BINANCE_WSS_URL
      - BINANCE_API_URL=$BINANCE_API_URL
      - ETHERSCAN_API_URL=$ETHERSCAN_API_URL
      - ETHERSCAN_API_KEY=$ETHERSCAN_API_KEY
    stdin_open: true
    tty: true

volumes:
  dbdata:
